### ISSUE TITLE
Login Screen > Supporters

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#29]
Summary: At the login screen the supporters modal should have logos in the following order:
1. Libro
2. Web Alchemists and Mika Software on the same line
3. Viva Canada (I will provide a website for this later)

These should each have working website links.

**Comment by viralrain** [comment]
what's the website for viva canada? I can't seem to find it

**Comment by rodolfomartinez** [comment]
Ok, Viva Canada site is not live yet.
