### ISSUE TITLE
Menu > Profile UI Missing

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#32]
Summary:
The Profile UI is missing. This should load a new page with the following elements
Firstname / Lastname
Level and XP
Current goals
Past goals (this is a link to past goals obtained, and the XP earned for each)
Badges (these will be small icons like gaming type trophies, we could maybe use font awesome icons?)
Date joined
Signup for E-Mail newsletter - there should be a chechbox beside this, and if they hit it a field appears below with an OK button beside it which submits their email to the database.

**Comment by viralrain** [comment]
need profile design reviewed, can see it at http://appdemo.oinweb.ca/profile.html
