### ISSUE TITLE
Modal > You've earned a new FLY Badge!

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#34]
Summary:
We need to create a modal that shows up when someone earns a badge. It should be titled

<Header>You've earned a new FLY Badge!</Header>

<text>Congratulations! You've earned a shiny new badge for your collection! Keep up the good work and be sure to let your friends know :-)</text>
(badge images goes here)
(social sharing goes here)

**Comment by viralrain** [comment]
modal test page created for testing out all of these modals, currently I used share-button which is a jquery library for share buttons.  I initially was going with the default share buttons provided by facebook, twitter and google+ but they didn't look all the same size and stuff, so I think this library looks a lot better.
https://github.com/carrot/share-button

**Comment by rodolfomartinez** [comment]
Ok where can I view this in app Demo?
