### ISSUE TITLE
Course Quiz UI

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#39]
Summary:
Each course ends with a quiz, consisting of 8 screens. Screen 1 is an introduction to the quiz, and has a Start button at the bottom. The next five screens are questions, once quiz per screen, multiple choice, with forward back buttons and submit at the end. Screen 7 is Submit your answers type screen, and Screen 8 either gives the student: 
1. a passing grade (if they scored at least 3 out of 5) as well as a badge for completing the course. After this the student can go back to their dashboard.
2 a continue screen (that looks like a game continue screen) that lets them go back to their dashboard or try again.

**Comment by viralrain** [comment]
Course quiz ui is working, just needs to be prettied up a bit I think, will review with @rodolfomartinez tomorrow
