### ISSUE TITLE
Privacy policy modal 

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#40]
Summary:
When clicking the privacy policy modal not all the text can be read as there is no scroll bar.

**Comment by viralrain** [comment]
just swipe up or down and it should scroll

**Comment by rodolfomartinez** [comment]
yeah but wont work on desktop

On Fri, Jan 15, 2016 at 2:55 PM, Chad Smith <notifications@github.com>
wrote:

> just swipe up or down and it should scroll
>
> On 01/15/2016 02:50 PM, rodolfomartinez wrote:
> >
> > Assigned #40 <https://github.com/Oinweb/py-fly/issues/40> to
> > @viralrain <https://github.com/viralrain>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Oinweb/py-fly/issues/40#event-516548337>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Oinweb/py-fly/issues/40#issuecomment-172067332>.
>



-- 
Sincerely,
Rodolfo Martinez
(519)521-3135 / (281)674-5103
Skype: rodolfo-reimar
CEO The Shooting Star Press inc.
www.LuchaComics.com

Be sure to follow @LuchaComics !
