### ISSUE TITLE
App Badges

### ISSUE THREAD

**Issue by bartmika** [Oinweb/py-fly#73]
Badges
~~At sign in: (title)The Quest Begins (description)You’ve begin your financial literacy journey. Awesome :-)~~

~~Level 2: (title)Level 2 (description)Keep at it - there’s a lot left to learn!~~

~~Level 3: (title)Level 3 (description)Good work! Keep it up!~~

~~Level 4: (title)Level 4 (description)You’re getting pretty good at this!~~

~~Level 5: (title)Level 5 (description)Wow, you’re dedicated!~~

~~Level 6: (title)Level 6 (description)Financial literacy isn’t so bad, is it?~~

~~Level 7: (title)Level 7 (description)You’re learning quite a bit, huh?~~

~~Level 8: (title)Level 8 (description)Almost there…~~

~~Level 9: (title)Level 9 (description)Financial guru~~

~~Level 10: (title)Level 10 (description)You made it! Keep hitting those goals :-)~~

Education Badges:
~~(title)First Course Complete (description)Great - now try another one!~~
only on first course complete sharing (title)Knowledge Sharer (description)Thanks for letting your friends know! 
~~(title)Completed Finances 101 (description)Great, now try Finance II!~~
~~(title)Completed Finances II (description)You did it!~~
~~(title)Completed Saving & Budgeting 101 (description)Great, now try Saving & Budgeting II!~~
~~(title)Completed Saving & Budgeting II (description)You did it!~~
~~(title)Completed Credit Score 101 (description)Great, now try Credit Score II!~~
~~(title)Completed Credit Score II (description)You did it!~~

Goal Badges:
~~(title)First goal achieved (description)You hit your first goal! Awesome!
*only at first goal share (title)Goal Sharing (description)Be proud of hitting your goals!~~

~~(title)First goal failed (description)Don’t give up!~~

~~(title)First savings goal achieved (description)Great saving! Keep it up!~~

~~(title)First credit goal achieved (description)Good job!~~

~~(title)First big goal achieved (description)That wasn’t so hard, now was it?~~

~~*awarded when 3 savings goals are hit (title)Savings champ (description)Great saving! Keep it up!~~

~~*awarded when 3 credit scores goals are hit (title)Credit score champ (description)Good job!~~

~~*awarded when 3 big goals are hit (title)Big saver! (description)That wasn’t so hard, now was it?~~

Resources:
~~Clicking the first resource in each category is worth a badge. Sharing the resources page socially gets them a badge.~~

**Comment by rodolfomartinez** [comment]
At sign in: (title)The Quest Begins (description)You’ve begin your financial literacy journey. Awesome :-)
Badge icon: fa-fort-awesome

Level 2: (title)Level 2 (description)Keep at it - there’s a lot left to learn!
Badge icon: smile-o

Level 3: (title)Level 3 (description)Good work! Keep it up!
Badge icon: thumbs-up

Level 4: (title)Level 4 (description)You’re getting pretty good at this! 
Bade icon: check-square-o

Level 5: (title)Level 5 (description)Wow, you’re dedicated!
Badge icon: user-plus

Level 6: (title)Level 6 (description)Financial literacy isn’t so bad, is it?
Badge: 

Level 7: (title)Level 7 (description)You’re learning quite a bit, huh?
Badge Icon: 

Level 8: (title)Level 8 (description)Almost there…
Badge Icon: puzzle-piece

Level 9: (title)Level 9 (description)Financial guru
Badge Icone: flash

Level 10: (title)Level 10 (description)You made it! Keep hitting those goals :-)
Badge icon: graduation-cap

Education Badges:
(title)First Course Complete (description)Great - now try another one!
*only on first course complete sharing (title)Knowledge Sharer (description)Thanks for letting your friends know! 

(title)Completed Finances 101 (description)Great, now try Finance II!
(title)Completed Finances II (description)You did it!
(title)Completed Saving & Budgeting 101 (description)Great, now try Saving & Budgeting II!
(title)Completed Saving & Budgeting II (description)You did it!
(title)Completed Credit Score 101 (description)Great, now try Credit Score II!
(title)Completed Credit Score II (description)You did it!

Can we used the same badge for all, just different colours: university

Goal Badges:
(title)First goal achieved (description)You hit your first goal! Awesome!
*only at first goal share (title)Goal Sharing (description)Be proud of hitting your goals!
Badge icon: flag-o

(title)First goal failed (description)Don’t give up!
Badge Icon: User-times

(title)First savings goal achieved (description)Great saving! Keep it up!
Badge Icon: money

(title)First credit goal achieved (description)Good job!
Badge Icon: Credit-card-alt

(title)First big goal achieved (description)That wasn’t so hard, now was it?
Badge Icon: diamond

*awarded when 3 savings goals are hit (title)Savings champ (description)Great saving! Keep it up!
Badge Icon: money

*awarded when 3 credit scores goals are hit (title)Credit score champ (description)Good job!
Badge icon: Credit-card-alt

*awarded when 3 big goals are hit (title)Big saver! (description)That wasn’t so hard, now was it?
Badge icon: diamond
