### ISSUE TITLE
Share Badge / Level-up Public Share Page

### ISSUE THREAD

**Issue by bartmika** [Oinweb/py-fly#80]
Pretend the user clicked 'Share' and various options are available to the user like facebook, twitter, etc. Now pretend the user selected any of those. The message should be something like "I won the badge blah blah blah, check it out at this link... http://www.flyapp.com/share/666/".

What we need now is a UI page for that link. The purpose is that we provide a link that's public to everyone and communicates either the User's success (badge/xp levelup) and is accessible by non-registered users. Furthermore, new users will be *enticed* to join the site with a link somewhere at the bottom encouraging the user to go to the landpage.

I need you to create this UI page. Make sure it has:
* UI is stand-alone and *unique*
* Make sure the UI looks like an award or a celebration for the user.
* Has a title, body and icons
* Has a link to the landpage
* Uses jQuery-Mobile

**Comment by viralrain** [comment]
share-page.html
