### ISSUE TITLE
Need pictures for landing page

### ISSUE THREAD

**Issue by viralrain** [Oinweb/py-fly#83]
Need team pictures and contact info - twitter, facebook, linkedin - for the landing page team section

**Comment by bartmika** [comment]
Hi @viralrain, use the pictures from: http://cloudmasterstudios.com

**Comment by rodolfomartinez** [comment]
hey social media accounts should be as follows:

https://www.twitter.com/oinweb
https://www.facebook.com/oinweb/
https://plus.google.com/+OinwebCa/about
https://www.linkedin.com/company/ontario-immigrant-network?trk=company_logo

Thanks

On Mon, Mar 7, 2016 at 6:39 PM, Chad Smith <notifications@github.com> wrote:

> Closed #83 <https://github.com/Oinweb/py-fly/issues/83>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Oinweb/py-fly/issues/83#event-580968064>.
>



-- 
Sincerely,
Rodolfo Martinez
(519)521-3135 / (281)674-5103
Skype: rodolfo-reimar
CEO The Shooting Star Press inc.
www.LuchaComics.com

Be sure to follow @LuchaComics !
