### ISSUE TITLE
Google authentication

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#88]
Summary:
When I log in with google my name shows up as Null on the menu
![image](https://cloud.githubusercontent.com/assets/7537946/13880482/d5d584c2-ecf2-11e5-8ae3-1b0273fdaabd.png)

**Comment by bartmika** [comment]
Confirmed, I reproduced this error. Will investigate.

**Comment by bartmika** [comment]
Cannot reproduce this issue as I get this.

![screen shot 2016-03-22 at 12 38 12 pm](https://cloud.githubusercontent.com/assets/5767602/13959582/10f49ae4-f02b-11e5-868c-66f61ee2afed.png)
