### ISSUE TITLE
flyapp.ca CSS colours

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#91]
Summary:
Can we change the main colours (yellow) on the site to this

background: #820b02

on hover: #a70000

**Comment by bartmika** [comment]
Is this the Land Page or the inside of Fly App?

**Comment by rodolfomartinez** [comment]
Sorry landpage only

On Tue, Mar 22, 2016 at 12:13 PM, Bartlomiej Mika <notifications@github.com>
wrote:

> Is this the Land Page or the inside of Fly App?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Oinweb/py-fly/issues/91#issuecomment-199885889>
>



-- 
Sincerely,
Rodolfo Martinez
(519)521-3135 / (281)674-5103
Skype: rodolfo-reimar
CEO The Shooting Star Press inc.
www.LuchaComics.com

Be sure to follow @LuchaComics !

**Comment by bartmika** [comment]
Confirmed. Will implement.
