### ISSUE TITLE
Menu change

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#95]
Summary:
3 items in the menu
Dashboard
My Goals
Learning

Need to be moved up to the top of the menu, so basically it would become
Dashboard
My goals
Learning
Profile
...

**Comment by bartmika** [comment]
Here is the menu we currently have:
 ![screen shot 2016-03-22 at 12 21 45 pm](https://cloud.githubusercontent.com/assets/5767602/13959029/b1371e62-f028-11e5-967d-2f175768fdd5.png)
