### ISSUE TITLE
Video error

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#96]
Summary:
clicking on a course gives not found, it is looking for a .MP4 file; we need to switch it to support Youtube. You can view the error at
https://flyapp.ca/en/course/1/

**Comment by bartmika** [comment]
Confirmed bug. It appears we support YouTube.com videos but the ETL to load the videos was not done. I just ran the ETL on PROD and it now works. Here is what I see.

![screen shot 2016-03-22 at 12 15 36 pm](https://cloud.githubusercontent.com/assets/5767602/13958788/d3c84c68-f027-11e5-9235-f0950f70e797.png)
